#ifndef VERSION_H
#define VERSION_H

#define MCU_FIRMWARE_VERSION_MAJOR 1
#define MCU_FIRMWARE_VERSION_MINOR 0
#define MCU_FIRMWARE_VERSION_PATCH 3

#ifndef MANAFISH_RELEASE_VERSION
#define MANAFISH_RELEASE_VERSION "1.0.3"
#endif

#define MCU_FIRMWARE_RELEASE_VERSION MANAFISH_RELEASE_VERSION

#endif
